name: update readMe and completions

on:
  push:
    paths:
      - '**.rs'
      - '.github/workflows/update_readme'

permissions:
  contents: write

jobs:
  create-release:
    name: update-readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: |
          ./.github/workflows/update_readme examples
          if git diff --exit-code README.md > /dev/null; then
            echo "no changes in readme"
          else
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add README.md
            git commit -m "update readme"
            changes=true
          fi

          cargo build --release

          if git diff --exit-code completions/ > /dev/null; then
            echo "No changes in completions/"
          else
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add completions/
            git commit -m "update completions"
            changes=true
          fi

          if [ "$changes" = true ]; then
            git push
          fi
