# SPDX-License-Identifier: MIT

name: update readMe

on:
  push:
    paths:
      - '**.rs'
      - '.github/workflows/update_readme'
  workflow_dispatch:
    inputs:
      examples:
        description: 'whether to generate examples'
        required: true
        default: 'no_examples'

permissions:
  contents: write

jobs:
  create-release:
    name: update-readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: |
          ./.github/workflows/update_readme "${{ github.event.inputs.examples }}"
          if git diff --exit-code README.md > /dev/null; then
            echo "no changes in readme"
          else
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add README.md
            git commit -m "update readme"
            git push
          fi
