name: Update ReadMe and Completions

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  create-release:
    name: update-readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: |
          sed -i '/### \*--help\* Output/q' README.md
          help_output=$(cargo run -- --help)
          changes=false

          {
            echo -e "\`\`\`"
            echo "$help_output"
            echo -e "\`\`\`"
          } >> README.md
          if git diff --exit-code README.md > /dev/null; then
            echo "No changes in README"
          else
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add README.md
            git commit -m "update help output"
            changes=true
          fi

          cargo build --release

          if git diff --exit-code completions/ > /dev/null; then
            echo "No changes in completions/"
          else
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add completions/
            git commit -m "update completions"
            changes=true
          fi

          if [ "$changes_made" = true ]; then
            git push
          else
            echo "No changes to push"
          fi
